script_2:
  # Refer to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/image_retraining/retrain.py#L907
  bottlenecks_dir: /path/to/bottlenecks_dir
  distort_images:
    flip_left_right: True
    random_brightness: 2
    random_crop: 30
    random_scale: 20
  eval_step_interval: 10
  final_tensor_name: id_aircraft_final_tensor
  images_dir: /path/to/datasets/airliners
  learning_rate: 0.005
  models_dir: /path/to/models_dir
  num_training_steps_before_ending: 100
  output_labels: output_labels.txt
  percentages:
    testing: 20
    validation: 20
  pretrained_model: /path/to/models_dir/tensorflow_inception_graph_dec_2015.pb
  print_misclassified_test_images: True
  summaries_dir: /path/to/summaries_dir
  train_batch_size: 100
  train_on_labels: ["A321", "A340", "B747", "CRJ900"]
  test_batch_size: -1
  validation_batch_size: 100
